export type Winner2016Entry = {
  name: string;
  category: string;
  company: string;
};

export type Winner2016Section = {
  title: string;
  entries: Winner2016Entry[];
};

export const winner2016Image = '/assets/logo/Anil-Porter.jpg';

const technologyIconEntries: Winner2016Entry[] = [
  { name: 'Nilesh Sangoi', category: 'Analytics Icon', company: 'Meru Cab Company Pvt. Ltd.' },
  { name: 'Ajay Bakshi', category: 'Analytics Icon', company: 'Aegis Limited.' },
  { name: 'Anjani Kumar', category: 'Analytics Icon', company: 'Safeexpress Pvt. Ltd.' },
  {
    name: 'Makrand Sawant',
    category: 'Analytics Icon',
    company: 'Deepak Fertilisers & Petrochemicals Corporation Ltd.',
  },
  {
    name: 'Sabyasachi Chakraborty Thakur',
    category: 'Analytics Icon',
    company: 'Century Plyboards (I) Limited',
  },
  { name: 'Jai Thomas', category: 'Cloud Services Icon', company: 'Versé Innovation Pvt Ltd.' },
  { name: 'Sudesh Agarwal', category: 'CRM Icon', company: 'Sterling Holiday Resorts Limited.' },
  { name: 'Manish Sinha', category: 'CRM Icon', company: 'Vectus Industries Ltd.' },
  { name: 'Umesh Mittal', category: 'CRM Icon', company: 'Alchemy Capital Management Pvt Ltd.' },
  {
    name: 'N Jayantha Prabhu',
    category: 'Data Centre & Infrastructure Icon',
    company: 'Essar Group',
  },
  { name: 'Murty KRC', category: 'Data Centre & Infrastructure Icon', company: 'Deutsche Bank Ag' },
  {
    name: 'Ajay Srivastava',
    category: 'Data Centre & Infrastructure Icon',
    company: 'Spice Retail',
  },
  {
    name: 'Rajesh Saboo',
    category: 'Data Centre & Infrastructure Icon',
    company: 'Wadia Group (Bombay Dyeing)',
  },
  {
    name: 'Vivek Khare',
    category: 'Data Centre & Infrastructure Icon',
    company: 'Commonfloor.com',
  },
  { name: 'Ravi Kumar GS', category: 'Digital Icon', company: 'Gati Limited' },
  { name: 'Vijay Varshney', category: 'Digital Icon', company: 'Smollan India' },
  { name: 'Pratap Gharge', category: 'Digital Icon', company: 'Bajaj Electricals' },
  { name: 'Ajay Kumar Meher', category: 'Digital Icon', company: 'Sony Pictures Networks' },
  { name: 'Shailesh Joshi', category: 'ERP Icon', company: 'Godrej Industries' },
  { name: 'Kamal Karnataka', category: 'ERP Icon', company: 'RJ Corp' },
  { name: 'Abhijit Chatterjee', category: 'ERP Icon', company: 'KARAM CHAND THAPAR GROUP' },
  { name: 'Vijay Bhaskar', category: 'ERP Icon', company: 'Visa Steel' },
  { name: 'Suresh Kumar', category: 'ERP Icon', company: 'Grant Thornton' },
  { name: 'Rupesh Nain', category: 'IoT Icon', company: 'JCB India' },
  { name: 'Manoj Kumar', category: 'IoT Icon', company: 'ACME Group' },
  { name: 'Harsh Arora', category: 'Mobility Icon', company: 'Hindustan Power' },
  { name: 'Prasenjit Mukherjee', category: 'Mobility Icon', company: 'BSES Power (Reliance ADAG)' },
  { name: 'Rajendra Deshpande', category: 'Mobility Icon', company: 'Intelenet Global Services' },
  { name: 'Prasad PVJ', category: 'Mobility Icon', company: 'Hafele' },
  { name: 'Pankaj Pandey', category: 'Mobility Icon', company: 'IDBI Federal Life Insurance' },
  { name: 'Sunil Mehta', category: 'SaaS Icon', company: 'J. Walter Thompson South Asia' },
  { name: 'Jayant Magar', category: 'SaaS Icon', company: 'AMW Motors' },
  { name: 'Kiran Komatla', category: 'SaaS Icon', company: 'Burger King India' },
  { name: 'Amit Phadke', category: 'SaaS Icon', company: 'Accelya Kale' },
  { name: 'Ved Prakash Nirbhaya', category: 'SaaS Icon', company: 'Tech Mahindra' },
  { name: 'Srirangarajan VS', category: 'SaaS Icon', company: 'Grasim' },
  {
    name: 'Shiju Rawther A',
    category: 'Security Icon',
    company: 'Credit Information Bureau India (CIBIL)',
  },
  { name: 'Vikas Arora', category: 'Security Icon', company: 'Toluna India' },
  { name: 'Hariharan Subramanian', category: 'Security Icon', company: 'Sattva Group' },
  { name: 'Ajit Manocha', category: 'Security Icon', company: 'Syngene International' },
  { name: 'Shiv Kumar Bhasin', category: 'Transformation Icon', company: 'State Bank Of India' },
  { name: 'Radhakrishnan G', category: 'Transformation Icon', company: 'BIOCON' },
  {
    name: 'Tarun Pandey',
    category: 'Transformation Icon',
    company: 'Aditya Birla Financial Services',
  },
  { name: 'Sendil Kumar V', category: 'Transformation Icon', company: 'Shriram Value Services' },
  { name: 'Muralidharan Ramachandran', category: 'Transformation Icon', company: 'Syntel' },
  { name: 'Vikas Grover', category: 'Transformation Icon', company: 'Vodafone' },
  { name: 'Anthony Thomas', category: 'Transformation Icon', company: 'General Electric' },
  {
    name: 'Avinash Velhal',
    category: 'Unified Communications Icon',
    company: 'Atos India Pvt Ltd',
  },
  { name: 'Kamal Goel', category: 'Unified Communications Icon', company: 'Anand Rathi' },
  {
    name: 'Sanjiv Kumar Jain',
    category: 'Unified Communications Icon',
    company: 'SPARK MINDA, ASHOK MINDA GROUP',
  },
  { name: 'Monika Phartyel', category: 'Digital Icon', company: '3M India' },
  { name: 'Puneet Kaur Kohli', category: 'Digital Icon', company: 'Bajaj Capital' },
  { name: 'Sachin Jain', category: 'IT, BPO & ITES Icon', company: 'Evalueserve' },
  { name: 'Subrata Dey', category: 'SaaS Icon', company: 'Godrej Consumer' },
  { name: 'Subramaniam V', category: 'Engineering Icon', company: 'United Technologies – OTIS' },
  { name: 'Sachin Gupta', category: 'Data Centre & Infrastructure Icon', company: 'Havells' },
];

const businessIconEntries: Winner2016Entry[] = [
  { name: 'Lalit Popli', category: 'Asset Management Icon', company: 'ICICI Pru AMC' },
  { name: 'Subhojit Roy', category: 'Asset Management Icon', company: 'SBI Mutual Funds' },
  {
    name: 'T.G. Dhandapani',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'TVS Motor Company',
  },
  {
    name: 'Om Prakash Singh',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Sona Koyo Steering Systems',
  },
  {
    name: 'Pratap Pat Joshi',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Mercedes Benz India',
  },
  {
    name: 'Rajeev Mittal',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Endurance Technologies',
  },
  {
    name: 'Vijay Sethi',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Hero MotoCorp',
  },
  { name: 'Shiv Kumar Bhasin', category: 'Banking Icon', company: 'State Bank Of India' },
  { name: 'Rajesh Bhasin', category: 'Banking Icon', company: 'Societe Generale' },
  { name: 'Sanjay Narkar', category: 'Banking Icon', company: 'IDFC' },
  { name: 'Anup Purohit', category: 'Banking Icon', company: 'YES Bank' },
  { name: 'Aruna Rao', category: 'Banking Icon', company: 'Kotak Bank' },
  { name: 'Munish Mittal', category: 'Banking Icon', company: 'HDFC Bank' },
  { name: 'Ashok Jade', category: 'Chemicals Icon', company: 'Shalimar Paints' },
  { name: 'Balaji A', category: 'Chemicals Icon', company: 'United Phosphorous' },
  { name: 'Manish Choksi', category: 'Chemicals Icon', company: 'Asian Paints Limited' },
  { name: 'Vinod Bidarkoppa', category: 'Diversified Group Icon', company: 'Future Group' },
  { name: 'Jayantha Prabhu', category: 'Diversified Group Icon', company: 'Essar Group' },
  { name: 'Ramandeep Singh Virdi', category: 'Diversified Group Icon', company: 'Interglobe' },
  { name: 'Anthony Thomas', category: 'Diversified Group Icon', company: 'General Electric' },
  { name: 'Shailesh Joshi', category: 'Diversified Group Icon', company: 'Godrej Industries' },
  { name: 'Rahul Mahajan', category: 'Diversified Group Icon', company: 'K Raheja Corp' },
  { name: 'Austin Gomes', category: 'E-commerce Icon', company: 'People Interactive Group' },
  { name: 'Aneesh Nair', category: 'E-commerce Icon', company: 'NDTV E-Commerce' },
  { name: 'Kishore Daryanani', category: 'Engineering Icon', company: 'Alfa Laval' },
  { name: 'Prasad PVJ', category: 'Engineering Icon', company: 'Hafele' },
  { name: 'Jagdish Lomte', category: 'Engineering Icon', company: 'Thermax' },
  { name: 'Prakash Dharmani', category: 'Manufacturing Icon', company: 'Essel Propack' },
  { name: 'Subramaniam V', category: 'Engineering Icon', company: 'United Technologies' },
  { name: 'Mukesh Kumar Jain', category: 'Financial Services Icon', company: 'Reliance Capital' },
  {
    name: 'Harish Sharma',
    category: 'Financial Services Icon',
    company: 'Toyota Financial Services',
  },
  {
    name: 'Mani Kant Singh R',
    category: 'Financial Services Icon',
    company: 'Orbis Financial Corporation',
  },
  { name: 'Sammeer Saurabh', category: 'Financial Services Icon', company: 'HDFC Securities' },
  {
    name: 'Sankarson Banerjee',
    category: 'Financial Services Icon',
    company: 'National Stock Exchange of India Limited (NSE)',
  },
  { name: 'Yagnesh Parikh', category: 'Financial Services Icon', company: 'ICICI Securities' },
  { name: 'Kalpana Maniar', category: 'Financial Services Icon', company: 'Edelweiss' },
  { name: 'Ranendra Datta', category: 'FMCG Icon', company: 'SAB Miller India' },
  { name: 'Girish Rao', category: 'FMCG Icon', company: 'Marico Limited' },
  { name: 'Radhakrishnan G', category: 'Healthcare & Pharma Icon', company: 'BIOCON' },
  { name: 'Jitendra Mishra', category: 'Healthcare & Pharma Icon', company: 'Wanbury' },
  {
    name: 'Veneeth Purushotaman',
    category: 'Healthcare & Pharma Icon',
    company: 'Fortis Healthcare',
  },
  { name: 'Girish Kulkarni', category: 'Healthcare & Pharma Icon', company: 'Cytecare Hospitals' },
  { name: 'Venkat Iyer', category: 'Healthcare & Pharma Icon', company: 'Wockhardt' },
  { name: 'Nandkishor Dhomne', category: 'Healthcare & Pharma Icon', company: 'Manipal Hospitals' },
  { name: 'Munender Soperna', category: 'Healthcare & Pharma Icon', company: 'Dr. Lal Pathlabs' },
  { name: 'Thomson Thomas', category: 'Insurance Icon', company: 'HDFC Life' },
  { name: 'Goutam Dutta', category: 'Insurance Icon', company: 'ICICI Lombard' },
  {
    name: 'Sanjeev Agrawal',
    category: 'Insurance Icon',
    company: 'Apollo Munich Health Insurance',
  },
  { name: 'MG Raghuraman', category: 'IT, BPO & ITES Icon', company: 'MPHASIS' },
  { name: 'Mohammad Wasim', category: 'IT, BPO & ITES Icon', company: 'Sapient Corporation' },
  { name: 'Nilesh Sangoi', category: 'Logistics Icon', company: 'Meru Cab Company' },
  { name: 'G.S. Ravi Kumar', category: 'Logistics Icon', company: 'Gati Limited' },
  { name: 'Anjani Kumar', category: 'Logistics Icon', company: 'Safexpress' },
  { name: 'Prasad Patil', category: 'Logistics Icon', company: 'JM Baxi Group' },
  { name: 'Shreesh Patwardhan', category: 'Logistics Icon', company: 'Dynamic Logistics' },
  { name: 'Sriram Naganathan', category: 'Insurance Icon', company: 'Liberty Videocon Insurance' },
  { name: 'Bhushan Akerkar', category: 'Manufacturing Icon', company: 'Hindalco' },
  { name: 'Rajat Sharma', category: 'Manufacturing Icon', company: 'Atul Limited' },
  { name: 'Rajiv Kumar Singla', category: 'Manufacturing Icon', company: 'ACC Ltd.' },
  { name: 'Milind Khamkar', category: 'Manufacturing Icon', company: 'Supermax' },
  { name: 'Subodh Dubey', category: 'Manufacturing Icon', company: 'Ballarpur Industries' },
  { name: 'Yogesh Zope', category: 'Manufacturing Icon', company: 'Bharat Forge' },
  { name: 'Sunil Mehta', category: 'Media Icon', company: 'J. Walter Thompson' },
  { name: 'Jai Daga', category: 'Media Icon', company: 'Viacom 18 Media' },
  { name: 'Rajat Nigam', category: 'Media Icon', company: 'Network18 Media' },
  { name: 'Ritu Madbhavi', category: 'Media Icon', company: 'FCB Ulka Advertising' },
  { name: 'Sayed Peerzade', category: 'Media Icon', company: 'Reliance Entertainment Group' },
  { name: 'Anil Shankar', category: 'Retail Icon', company: 'Shoppers Stop' },
  { name: 'Deena Dayalan K', category: 'Retail Icon', company: 'Sears' },
  { name: 'Ranjit Satyanath', category: 'Retail Icon', company: 'Infiniti Retail (Croma)' },
  { name: 'Meheriar Patel', category: 'Retail Icon', company: 'The Mobile Store' },
  { name: 'Shreesh Palekar', category: 'Retail Icon', company: 'Raymond Limited' },
  { name: 'Avinash Mittal', category: 'Telecom Icon', company: 'Telenor India' },
  { name: 'Vikas Grover', category: 'Telecom Icon', company: 'Vodafone' },
  { name: 'Manoj Shrivastava', category: 'Telecom Icon', company: 'Sistema Shyam Teleservices' },
  {
    name: 'Harish Chandra',
    category: 'Travel & Hospitality Icon',
    company: 'Sarovar Hotels & Resorts',
  },
  { name: 'Raman Rama', category: 'Travel & Hospitality Icon', company: 'JHM Hotels' },
  {
    name: 'Shrikant Kulkarni',
    category: 'Travel & Hospitality Icon',
    company: 'IntelliStay Hotels',
  },
  {
    name: 'Vijay Choudhary',
    category: 'Travel & Hospitality Icon',
    company: 'HRH Group of Hotels',
  },
  { name: 'Khushru Siganoporoia', category: 'Travel & Hospitality Icon', company: 'Taj Hotels' },
  { name: 'Sanjay Prasad', category: 'Utilities Icon', company: 'Tata Power' },
  { name: 'Anil Garg', category: 'Transformation Icon', company: 'Dabur India Limited' },
];

export const winner2016Sections: Winner2016Section[] = [
  {
    title: 'Technology Icons',
    entries: technologyIconEntries,
  },
  {
    title: 'Business Icons',
    entries: businessIconEntries,
  },
];
