export type Winner2022Entry = {
  name: string;
  category: string;
  company: string;
};

export type Winner2022Section = {
  title: string;
  entries: Winner2022Entry[];
};

export const winner2022Image = '/assets/logo/Anil-Porter.jpg';

const technologyIconEntries: Winner2022Entry[] = [
  { name: 'Farhan Khan', category: 'Analytics Icon', company: 'Allied Blenders & Distillers' },
  { name: 'Satish Panchapakesan', category: 'Analytics Icon', company: 'Arvind Fashions' },
  { name: 'Mahendra Upadhyay', category: 'Analytics Icon', company: 'BARC India' },
  { name: 'Yoganand Tadepallli', category: 'Analytics Icon', company: 'PGP Glass' },
  { name: 'VS Srirangarajan', category: 'Analytics Icon', company: 'Grasim Industries' },
  {
    name: 'Navratan Bohra',
    category: 'Analytics Icon',
    company: 'Anand Rathi Shares & Stock Brokers',
  },
  { name: 'Hemang Mehta', category: 'Analytics Icon', company: 'Loreal India' },
  {
    name: 'Ashish Shrivastava',
    category: 'Artificial Intelligence Icon',
    company: 'Financial Software and System',
  },
  {
    name: 'Piyush Srivastav',
    category: 'Artificial Intelligence Icon',
    company: 'The Muthoot Group',
  },
  { name: 'Sanjay Nagpal', category: 'Artificial Intelligence Icon', company: 'TV Today Network' },
  { name: 'Suresh Nadar', category: 'Artificial Intelligence Icon', company: "Dr Batra's" },
  { name: 'Raman Pillai', category: 'Cloud Icon', company: 'Ather Energy' },
  { name: 'Abhishek Gupta', category: 'Cloud Icon', company: 'Dish TV' },
  { name: 'Ajay Bharwani', category: 'Cloud Icon', company: 'Writer Corporation' },
  { name: 'Madhusudan Warrier', category: 'Cloud Icon', company: 'Mirae Asset Capital Markets' },
  { name: 'Piyush Mistry', category: 'Cloud Icon', company: 'Dvara Smart Gold' },
  { name: 'Anuj Joshi', category: 'Collaboration Icon', company: 'Evalueserve' },
  { name: 'G.S. Ravi Kumar', category: 'Collaboration Icon', company: 'Gati Kintetsu Express' },
  { name: 'Shobhana Lele', category: 'Collaboration Icon', company: 'The Bombay Dyeing and Mfg' },
  { name: 'Subhakar Rudra', category: 'Collaboration Icon', company: 'WPIL' },
  { name: 'Abhishek Arora', category: 'Collaboration Icon', company: 'K Raheja Corp' },
  { name: 'Khushru Mistry', category: 'CRM Icon', company: 'Eureka Forbes' },
  { name: 'Vivek Digumarti', category: 'CRM Icon', company: 'Laurus Labs' },
  {
    name: 'Badar Afaq',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'Antara Senior Living',
  },
  {
    name: 'Rajat Nigam',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'NETWORK18 (VIACOM18 + TV18, NW18)',
  },
  {
    name: 'Subodh Dubey',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'Suzlon Energy',
  },
  {
    name: 'Abhijeet Bhalerao',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'Nuvoco Vistas Corp',
  },
  {
    name: 'Vinod Deshmukh',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'Haldiram Foods International',
  },
  { name: 'Amit Phadke', category: 'Datacenter & IT Infrastructure Icon', company: 'Toll Group' },
  { name: 'Binod Roy', category: 'Digital Icon', company: 'Wonder Home Finance' },
  { name: 'Sajith Chakkingal', category: 'Digital Icon', company: 'TMF Group' },
  { name: 'Rajiv Arora', category: 'Digital Icon', company: 'Siemens AG' },
  { name: 'Rohit Kilam', category: 'Digital Icon', company: 'CMS' },
  { name: 'Venkatesh Babu', category: 'Digital Icon', company: 'Coffee Day Global' },
  { name: 'Sreeji Gopinathan', category: 'Digital Icon', company: 'Lupin' },
  { name: 'Dharmendra Kumar', category: 'Digital Icon', company: 'Waycool Foods and Products' },
  { name: 'Vineet Bansal', category: 'ERP Icon', company: 'Surya Roshni' },
  { name: 'Kumaresan Muthuramalingam', category: 'ERP Icon', company: 'Unichem Laboratories' },
  { name: 'Ravi Sharma', category: 'ERP Icon', company: 'Wanbury' },
  { name: 'Yogesh Dadke', category: 'IoT Icon', company: 'Adient' },
  { name: 'Satej Revankar', category: 'IoT Icon', company: 'Fiat India Automobiles' },
  { name: 'Puneesh Lamba', category: 'IoT Icon', company: 'Shahi Exports' },
  { name: 'Atanu Pramanic', category: 'IT Modernization Icon', company: 'Hindalco Industries' },
  { name: 'Rahul Borse', category: 'IT Modernization Icon', company: 'RPG life Sciences' },
  { name: 'Sachin Gupta', category: 'IT Modernization Icon', company: 'Usha International' },
  { name: 'Niraj Godiwala', category: 'IT Services Icon', company: 'Knight Frank India' },
  { name: 'Vimit Kapur', category: 'IT Services Icon', company: 'PACCAR India' },
  {
    name: 'Kushal Kumar Varshney',
    category: 'IT Services Icon',
    company: 'Virescent Infrastructure',
  },
  { name: 'Sanjay Chowdhry', category: 'Mobility Icon', company: 'Hamdard Laboratories' },
  { name: 'Kiran Komatla', category: 'Mobility Icon', company: 'Restaurant Brands Asia' },
  { name: 'Dixson Almeida', category: 'Risk Management Icon', company: 'IDFC Asset Management' },
  { name: 'Vivek Zakarde', category: 'Risk Management Icon', company: 'IKS Health' },
  { name: 'Shweta Srivastava', category: 'Risk Management Icon', company: 'Paul Merchants' },
  { name: 'Pushkar Rege', category: 'Risk Management Icon', company: 'UPL' },
  { name: 'Kishore Hirani', category: 'RPA Icon', company: 'Amara Raja' },
  { name: 'Avadhut Parab', category: 'RPA Icon', company: 'Parle Agro' },
  { name: 'Nayan Desai', category: 'RPA Icon', company: 'WNS Global Services' },
  { name: 'Dhaval Pandya', category: 'RPA Icon', company: 'Piramal Enterprises' },
  { name: 'Gaurav Pandey', category: 'SaaS Icon', company: 'Delhivery' },
  { name: 'Naseem Halder', category: 'Security Icon', company: 'ACKO General Insurance' },
  { name: 'Satyanarayana Kasturi', category: 'Security Icon', company: 'Ashok Piramal Group' },
  { name: 'Navaneethan M', category: 'Security Icon', company: 'Groww' },
  { name: 'Shibin Chulliparambil', category: 'Security Icon', company: 'Mafatlal Industries' },
  { name: 'Anis Pankhania', category: 'Security Icon', company: 'Capgemini Technology Services' },
  { name: 'Ayaskant Mohapatra', category: 'System Integration Icon', company: 'BOB Financial' },
  {
    name: 'Dr. Makarand Sawant',
    category: 'System Integration Icon',
    company: 'Deepak Fertilisers And Petrochemicals',
  },
  { name: 'Jijy Oommen', category: 'Transformation Icon', company: 'Aavas Financiers' },
  { name: 'Ganesh Ramachandran', category: 'Transformation Icon', company: 'Alkem Laboratories' },
  { name: 'Rajesh Uppal', category: 'Transformation Icon', company: 'Maruti Suzuki India' },
  {
    name: 'Ananth Subramanian',
    category: 'Unified Communications Icon',
    company: 'Kotak Mahindra Asset Mgt',
  },
  {
    name: 'Selestin Thomas',
    category: 'Unified Communications Icon',
    company: 'Nissan Digital India',
  },
  {
    name: 'Girish Koppar',
    category: 'Unified Communications Icon',
    company: 'Wockhardt Hospitals',
  },
  { name: 'CK Prasad', category: 'Virtualization Icon', company: 'RailTel-Ministry of Railways' },
  { name: 'Binita Prasad', category: 'Virtualization Icon', company: 'Saint-Gobain' },
];

const businessIconEntries: Winner2022Entry[] = [
  {
    name: 'Asish Karunakaran',
    category: 'Asset Management Icon',
    company: 'ICICI Prudential Asset Management',
  },
  { name: 'A Shiju Rawther', category: 'Asset Management Icon', company: 'SBI Mutual Fund' },
  { name: 'Raghunatha Reddy', category: 'Asset Management Icon', company: 'UTI Asset Management' },
  {
    name: 'Rajeev Mittal',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Endurance Technologies',
  },
  {
    name: 'Rucha Nanavati',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Mahindra Group',
  },
  {
    name: 'Sharad Kumar Agarwal',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'JK Tyre & Industries',
  },
  { name: 'Sanjay Gupta', category: 'Banking Icon', company: 'Kotak Mahindra Bank' },
  { name: 'Vinod Kumar K B', category: 'Banking Icon', company: 'Fino Payments Bank' },
  { name: 'Nilesh Sangoi', category: 'Banking Icon', company: 'Fincare Small Finance Bank' },
  { name: 'Amit Jaokar', category: 'Banking Icon', company: 'NKGSB Bank' },
  { name: 'Sankarson Banerjee', category: 'Banking Icon', company: 'RBL Bank' },
  { name: 'Harnath Babu', category: 'Consulting Icon', company: 'KPMG India' },
  { name: 'Sanjay Kotha', category: 'Diversified Group Icon', company: 'Adani Ports and SEZ' },
  { name: 'Vineet Jaiswal', category: 'Diversified Group Icon', company: 'Vedanta' },
  { name: 'Manuj Desai', category: 'Diversified Group Icon', company: 'Sterlite Technologies' },
  { name: 'Mani Mulki', category: 'Diversified Group Icon', company: 'Kedaara Capital' },
  { name: 'Jai Prakash Sharma', category: 'E-Commerce Icon', company: 'InfoEdge India' },
  { name: 'Prakash Ramachandran', category: 'EDTech Icon', company: 'Think and Learn (Byjus)' },
  { name: 'Prosenjit Sengupta', category: 'Engineering Icon', company: 'Thermax' },
  { name: 'Rajkumar Ayyella', category: 'Engineering Icon', company: 'KEC International' },
  { name: 'Srinivasa Rao Kollipara', category: 'Engineering Icon', company: 'L&T IDPL' },
  { name: 'Yogesh Zope', category: 'Engineering Icon', company: 'Bharat Forge' },
  { name: 'Kersi Tavadia', category: 'Financial Services Icon', company: 'BSE' },
  {
    name: 'Sendil Kumar Venkatesan',
    category: 'Financial Services Icon',
    company: 'Shriram Capital',
  },
  { name: 'Prasad Patil', category: 'Financial Services Icon', company: 'NCDEX eMarkets' },
  { name: 'Tarun Pandey', category: 'Financial Services Icon', company: 'Aditya Birla Capital' },
  { name: 'Shiv Kumar Bhasin', category: 'Financial Services Icon', company: 'NSE India' },
  { name: 'Kamal Karnataka', category: 'FMCG Icon', company: 'RJ Corp' },
  { name: 'Sanjay Moralwar', category: 'Healthcare & Pharma Icon', company: 'Zydus Lifesciences' },
  { name: 'Ashok Nayak', category: 'Healthcare & Pharma Icon', company: 'IPCA Laboratories' },
  { name: 'Swapnil Wadhwa', category: 'Healthcare & Pharma Icon', company: 'Aragen Life Sciences' },
  { name: 'Gaurav Kataria', category: 'Healthcare & Pharma Icon', company: 'Sai Life Sciences' },
  { name: 'Mukund K S', category: 'Healthcare & Pharma Icon', company: 'Eris Lifesciences' },
  { name: 'Kirti Patil', category: 'Insurance Icon', company: 'Kotak Life Insurance' },
  { name: 'Ayan De', category: 'Insurance Icon', company: 'Exide Life Insurance' },
  {
    name: 'Sourabh Chatterjee',
    category: 'Insurance Icon',
    company: 'Bajaj Allianz General Insurance',
  },
  { name: 'Goutam Datta', category: 'Insurance Icon', company: 'Bajaj Allianz Life Insurance' },
  { name: 'Pankaj Kumar Pandey', category: 'Insurance Icon', company: 'SBI General Insurance' },
  {
    name: 'Puneet Kaur Kohli',
    category: 'Insurance Icon',
    company: 'Universal Sompo General Insurance',
  },
  { name: 'Baljinder Singh', category: 'IT, BPO & ITES Icon', company: 'EXL Service' },
  { name: 'Meghan Nandgaonkar', category: 'IT, BPO & ITES Icon', company: 'Fujitsu' },
  { name: 'Debashis Singh', category: 'IT, BPO & ITES Icon', company: 'Mphasis' },
  {
    name: 'Sajith Kumar S',
    category: 'IT, BPO & ITES Icon',
    company: 'Happiest Minds Technologies',
  },
  { name: 'Narottam Sharma', category: 'IT, BPO & ITES Icon', company: 'Mastek' },
  {
    name: 'Sanjeev Kumar Jain',
    category: 'IT, BPO & ITES Icon',
    company: 'Integreon Managed Solutions',
  },
  { name: 'Sanjay Kukreja', category: 'IT, BPO & ITES Icon', company: 'eClerx Services' },
  { name: 'Jitendra Singh', category: 'Manufacturing Icon', company: 'JK Cement' },
  { name: 'Sudhir Kanvinde', category: 'Manufacturing Icon', company: 'The Supreme Industries' },
  { name: 'Kapil Pal', category: 'Manufacturing Icon', company: 'United Breweries' },
  { name: 'Rajesh Panchal', category: 'Manufacturing Icon', company: 'INOX AP' },
  { name: 'Sarbani Bhatia', category: 'Media & Entertainment Icon', company: 'Jagran Prakashan' },
  { name: 'Anurag Jain', category: 'NBFC Icon', company: 'Bajaj Housing Finance' },
  { name: 'Pankaj Khare', category: 'NBFC Icon', company: 'Indiabulls Housing Finance' },
  { name: 'Tushar Vagal', category: 'Real Estate Icon', company: 'L&T Realty' },
  { name: 'Samir V M', category: 'Real Estate Icon', company: 'Rustomjee' },
  { name: 'Vinod Kapote', category: 'Retail Icon', company: 'Trent' },
  { name: 'Anil Shankar', category: 'Retail Icon', company: 'Shoppers Stop' },
  { name: 'Kunal Dhingra', category: 'Secure Digital Workspace Icon', company: 'L&T Infotech' },
  { name: 'Apoorv Srivastava', category: 'Telecom Icon', company: 'British Telecom' },
  { name: 'Vinod Krishnan', category: 'Telecom Icon', company: 'Indus Towers' },
  { name: 'Ashish Mathur', category: 'Transport & Logistics Icon', company: 'Allcargo Group' },
  { name: 'Saugat Dutta', category: 'Transport & Logistics Icon', company: 'DP World' },
  { name: 'Vinod Bhat', category: 'Travel & Hospitality Icon', company: 'Tata SIA Airlines' },
  { name: 'Sanjay Prasad', category: 'Utilities Icon', company: 'RPSG CESC Power Group' },
];

export const winner2022Sections: Winner2022Section[] = [
  {
    title: 'Technology Icons',
    entries: technologyIconEntries,
  },
  {
    title: 'Business Icons',
    entries: businessIconEntries,
  },
];
