export type Winner2025Entry = {
  name: string;
  category: string;
  company: string;
};

export type Winner2025Section = {
  title: string;
  entries: Winner2025Entry[];
};

export const winner2025Image = '/assets/logo/Anil-Porter.jpg';

const technologyIconEntries: Winner2025Entry[] = [
  { name: 'Anil Porter', category: 'AI Icon', company: 'ITQ Technologies' },
  { name: 'Gaurav Duggal', category: 'AI Icon', company: 'Jio Platform' },
  { name: 'Sanjay Kumar Purohit', category: 'AI Icon', company: 'National Engineering Industries' },
  { name: 'Vamsi Ithamaraju', category: 'AI Icon', company: 'Axis Asset Management' },
  { name: 'Yogendra Singh', category: 'AI Icon', company: 'Barista Coffee Company' },
  { name: 'Ajay Bharwani', category: 'Analytics Icon', company: 'Writer Corporation' },
  { name: 'Mushtaq Ahmad', category: 'Analytics Icon', company: 'Movate' },
  { name: 'Rajneesh Singh', category: 'Analytics Icon', company: 'Rays Power Infra' },
  { name: 'Sivasubramanian M', category: 'Analytics Icon', company: 'JK Fenner' },
  { name: 'Yogendra Yadav', category: 'Analytics Icon', company: 'Sai Life Sciences' },
  { name: 'Badar Afaq', category: 'Cloud Icon', company: 'KCT Group' },
  { name: 'Dheepak Rajoo', category: 'Cloud Icon', company: 'Royal Sundaram General Insurance' },
  { name: 'Pankaj Kumar', category: 'Cloud Icon', company: 'Cent Bank Home Finance' },
  { name: 'Vinay Kumar', category: 'Cloud Icon', company: 'MMG Group' },
  { name: 'Ashok Sannabhadti', category: 'Collaboration Icon', company: 'Universal Nutriscience' },
  {
    name: 'Shobhana Lele',
    category: 'Collaboration Icon',
    company: 'The Bombay Dyeing And Manufacturing',
  },
  { name: 'Ajay Ajmera', category: 'CRM Icon', company: 'Rockman Industries' },
  { name: 'Anand Deodhar', category: 'CRM Icon', company: 'Force Motors' },
  { name: 'Navin Nathani', category: 'CRM Icon', company: 'Cohizon Life Sciences' },
  { name: 'Bhargab Dutta', category: 'Digital Icon', company: 'Century Plyboards (India)' },
  { name: 'Girish Hadkar', category: 'Digital Icon', company: 'Tata Realty And Infrastructure' },
  { name: 'Hemal Savla', category: 'Digital Icon', company: 'Shalina Healthcare' },
  { name: 'Satish Panchapakesan', category: 'Digital Icon', company: 'Appasamy Associates' },
  { name: 'Satish Pengal', category: 'Transformation Icon', company: 'Upstox' },
  { name: 'Subhendu Kesh', category: 'Digital Icon', company: 'JK Paper' },
  { name: 'Sudeep Dey', category: 'Digital Icon', company: 'HCG Enterprises' },
  {
    name: 'Avaneesh Kumar Vats',
    category: 'Edge Computing Icon',
    company: 'Techno Electric & Engineering',
  },
  { name: 'CK Prasad', category: 'Edge Computing Icon', company: 'Central Railway' },
  { name: 'Ashish Desai', category: 'ERP Icon', company: 'Grasim Industries' },
  { name: 'G. Venkateshwaran Iyer', category: 'ERP Icon', company: 'JSW Greentech' },
  { name: 'Jitender Verma', category: 'ERP Icon', company: 'PVR INOX' },
  { name: 'Nitin Jain', category: 'ERP Icon', company: 'Gravita India' },
  { name: 'Rajesh Kulkarni', category: 'ERP Icon', company: 'Piaggio Vehicles' },
  {
    name: 'Sunil Pahune',
    category: 'ERP Icon',
    company: 'Manas Agro Industries & Infrastructure',
  },
  { name: 'Dr. Vineet Bansal', category: 'ERP Icon', company: 'Surya Roshni' },
  { name: 'Ashish Dhagat', category: 'Gen AI Icon', company: 'Hector Beverages' },
  { name: 'Rucha Nanavati', category: 'Gen AI Icon', company: 'Mahindra & Mahindra' },
  {
    name: 'Partha Protim Mondal',
    category: 'Hardware Network & Storage Icon',
    company: 'Berger Paints India',
  },
  { name: 'Deepak Panda', category: 'IoT Icon', company: 'National Highways Infra Trust' },
  { name: 'Rajeev Mittal', category: 'IoT Icon', company: 'Endurance Technologies' },
  { name: 'Harsh Jha', category: 'IT Modernization Icon', company: 'Nuvama Group' },
  { name: 'Jegadeeswaran B', category: 'IT Modernization Icon', company: 'TVS Automobile' },
  { name: 'Satyavrat Mishra', category: 'IT Modernization Icon', company: 'Godrej Industries' },
  { name: 'Dharmendra Kumar', category: 'ML Icon', company: 'Tata Electronics' },
  { name: 'Anand Sinha', category: 'Productivity Icon', company: 'BirlaSoft' },
  { name: 'Manu Sharma', category: 'Productivity Icon', company: 'OnMobile Global' },
  { name: 'Ninad Raje', category: 'Productivity Icon', company: 'Jaquar' },
  { name: 'Ramanarayana Parhi', category: 'Productivity Icon', company: 'Alkem Laboratories' },
  { name: 'Anuj Joshi', category: 'RPA Icon', company: 'S&A Law Offices' },
  { name: 'Jagadeeswara Rao Sornapudi', category: 'RPA Icon', company: 'Kama Schachter' },
  { name: 'Neilmani Sahu', category: 'RPA Icon', company: 'JSW Paints' },
  { name: 'Pramod Gokhale', category: 'RPA Icon', company: 'Mankind Pharma' },
  { name: 'Rishabh Chhajer', category: 'RPA Icon', company: 'Allen Digital' },
  {
    name: 'Shweta Bhatnagar',
    category: 'RPA Icon',
    company: 'Symbiosis International University',
  },
  {
    name: 'Krishnamurthy Rajesh',
    category: 'Secure Digital Workspace Icon',
    company: 'Grey Orange',
  },
  { name: 'Anand Tomar', category: 'Security Icon', company: 'Allied Blenders & Distillers' },
  { name: 'Archie Jackson', category: 'Security Icon', company: 'Icedo Inc.' },
  { name: 'Ketan Karkhanis', category: 'Security Icon', company: 'Hindalco' },
  { name: 'Kiran Belsekar', category: 'Security Icon', company: 'Bandhan Life' },
  { name: 'Ravi Razdan', category: 'Security Icon', company: 'Jyothy Laboratories' },
  { name: 'Selestin T Thomas', category: 'Security Icon', company: 'Nissan Digital' },
  {
    name: 'Subhash Singh Punjabi',
    category: 'Security Icon',
    company: 'Deepak Fertilisers And Petrochemicals',
  },
  { name: 'Dr. Ravi Sharma', category: 'Software Icon', company: 'Wanbury' },
  { name: 'Bal Singh', category: 'Supply Chain Icon', company: 'Shahi Exports' },
  { name: 'Farhan Khan', category: 'Supply Chain Icon', company: 'Radico Khaitan' },
  {
    name: 'Gur Dayal Bhatnagar',
    category: 'Supply Chain Icon',
    company: 'Spark Minda Corporation',
  },
  { name: 'Raghubir Singh', category: 'Supply Chain Icon', company: 'Relaxo Footwears' },
  { name: 'Rupesh Nirgude', category: 'Supply Chain Icon', company: 'Prism Johnson' },
  { name: 'Apoorv Srivastava', category: 'Transformation Icon', company: 'BT Group' },
  { name: 'Harvinder Singh Banga', category: 'Transformation Icon', company: 'CJ Darcl Logistics' },
  { name: 'Hemang Mehta', category: 'Transformation Icon', company: 'Loreal India' },
  { name: 'Manoj Gautam', category: 'Transformation Icon', company: 'Maruti Suzuki' },
  { name: 'Suresh Vijayaraghavan', category: 'Transformation Icon', company: 'The Hindu Group' },
  { name: 'Venkatesh CR', category: 'Transformation Icon', company: 'RR Donnelley' },
];

const businessIconEntries: Winner2025Entry[] = [
  {
    name: 'Arpanarghya Saha',
    category: 'Asset Management Icon',
    company: 'Nippon India Mutual Fund',
  },
  { name: 'A Shiju Rawther', category: 'Asset Management Icon', company: 'SBI Mutual Fund' },
  {
    name: 'Dr. Tapan Sahoo',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Maruti Suzuki',
  },
  {
    name: 'Satej Revankar',
    category: 'Automobile & Auto Ancillaries Icon',
    company: 'Fiat India Automobile',
  },
  {
    name: 'Shraddha Ukalkar',
    category: 'Automobile & Auto Ancillaries Icon',
    company: 'Mercedes Benz India',
  },
  { name: 'Vinod Bhat', category: 'Automobiles & Auto Ancillaries Icon', company: 'Tata Autocomp' },
  {
    name: 'Vinod Gopinathan',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Ashok Leyland',
  },
  { name: 'Vishal Bhatia', category: 'Banking Icon', company: 'Canara Bank' },
  { name: 'Zuzar Tinwalla', category: 'Banking Icon', company: 'Standard Chartered Bank' },
  { name: 'Harnath Babu', category: 'Consulting Icon', company: 'KPMG' },
  { name: 'Jai Prakash Sharma', category: 'E-Commerce Icon', company: 'Infoedge India' },
  {
    name: 'Dr. Pradeep Pendse',
    category: 'Education Icon',
    company: 'Prin. L.N. Welinkar Institute of Management & Research',
  },
  { name: 'Rajkumar Ayyella', category: 'Engineering Icon', company: 'KEC International' },
  { name: 'Akanksha Garg', category: 'Financial Services Icon', company: 'HDFC Securities' },
  {
    name: 'Harish Gupta',
    category: 'Financial Services Icon',
    company: 'Credit Guarantee Fund Trust For Micro And Small Enterprises',
  },
  { name: 'Jyothirlatha B', category: 'Financial Services Icon', company: 'Godrej Capital' },
  {
    name: 'Madhusudan Warrier',
    category: 'Financial Services Icon',
    company: 'Mirae Asset Sharekhan',
  },
  {
    name: 'Pankaj Khare',
    category: 'Financial Services Icon',
    company: 'Bharat Financial Inclusion',
  },
  { name: 'Piyush Srivastav', category: 'Financial Services Icon', company: 'Muthoot Finance' },
  { name: 'Anil Sharma', category: 'FMCG Icon', company: 'Pepsico' },
  { name: 'Prosenjit Sengupta', category: 'FMCG Icon', company: 'ITC' },
  { name: 'Sanjay Joshi', category: 'FMCG Icon', company: 'Parle Products' },
  { name: 'Chirag Bharatia', category: 'Healthcare & Pharma Icon', company: 'Oracle Cerner' },
  { name: 'Pankaj Sharma', category: 'Healthcare & Pharma Icon', company: 'Hikal' },
  { name: 'Vamshi Bathini', category: 'Healthcare & Pharma Icon', company: 'CallHealth Services' },
  { name: 'Pankaj Kumar Pandey', category: 'Insurance Icon', company: 'SBI General Insurance' },
  { name: 'Rahul Chopra', category: 'Insurance Icon', company: 'PNB Metlife' },
  { name: 'Rohit Kilam', category: 'Insurance Icon', company: 'HDFC Life Insurance' },
  { name: 'Sunit Vakharia', category: 'Insurance Icon', company: 'Reliance Nippon Life Insurance' },
  {
    name: 'Yoganand Tadepalli',
    category: 'Insurance Icon',
    company: 'Insurance Information Bureau Of India',
  },
  { name: 'Jayant Goyal', category: 'IT, BPO & ITES Icon', company: 'Coforge' },
  { name: 'Nayan Desai', category: 'IT, BPO & ITES Icon', company: 'WNS Global Services' },
  { name: 'Dr. Avadhut Parab', category: 'Manufacturing Icon', company: 'Waaree Energies' },
  {
    name: 'Chetan Trivedi',
    category: 'Manufacturing Icon',
    company: 'Vedanta Resources and STL Digital',
  },
  { name: 'Debashish Roy', category: 'Manufacturing Icon', company: 'CEAT' },
  { name: 'Gyan Pandey', category: 'Manufacturing Icon', company: 'Voltas' },
  { name: 'Sharad Kumar Agrawal', category: 'Manufacturing Icon', company: 'JK Tyre & Industries' },
  { name: 'Sudip Mazumder', category: 'Manufacturing Icon', company: 'PGP Glass' },
  { name: 'Abhishek Gupta', category: 'Media & Entertainment Icon', company: 'Dish TV' },
  { name: 'Mahendra Upadhyay', category: 'Media & Entertainment Icon', company: 'BARC India' },
  {
    name: 'Sarbani Bhatia',
    category: 'Media & Entertainment Icon',
    company: 'Jagran Prakashan (Dainik Jagran)',
  },
  { name: 'Ayaskant Mohapatra', category: 'NBFC Icon', company: 'BOB Cards' },
  { name: 'Anand Chaudri', category: 'NBFC Icon', company: 'Tide Platform' },
  { name: 'Dominic Vijay Kumar', category: 'NBFC Icon', company: 'Namdev Finvest' },
  { name: 'Linson Paul', category: 'NBFC Icon', company: 'Muthoot Microfin' },
  { name: 'Naveen Gulati', category: 'Retail Icon', company: 'Modi Enterprises' },
  { name: 'Nikhil Bhushan', category: 'Retail Icon', company: 'Starbucks India' },
  { name: 'Rahul Puri', category: 'Retail Icon', company: 'Devyani International' },
  {
    name: 'Venkata Sudhakar Nagandla',
    category: 'Transport & Logistics Icon',
    company: 'ECU Worldwide',
  },
  { name: 'Atanu Kumar Pramanic', category: 'Utilities Icon', company: 'RPSG - CESC' },
  { name: 'Sanjeev Sinha', category: 'Utilities Icon', company: 'India Power Corporation' },
];

export const winner2025Sections: Winner2025Section[] = [
  {
    title: 'Technology Icons',
    entries: technologyIconEntries,
  },
  {
    title: 'Business Icons',
    entries: businessIconEntries,
  },
];
