export type Winner2023Entry = {
  name: string;
  category: string;
  company: string;
};

export type Winner2023Section = {
  title: string;
  entries: Winner2023Entry[];
};

export const winner2023Image = '/assets/logo/Anil-Porter.jpg';

const technologyIconEntries: Winner2023Entry[] = [
  { name: 'Anurag Jain', category: 'Analytics Icon', company: 'Bajaj Housing Finance' },
  { name: 'Suresh Nadar', category: 'Analytics Icon', company: "Dr Batra's Group" },
  { name: 'Sudip Mazumder', category: 'Analytics Icon', company: 'Larsen & Toubro' },
  {
    name: 'Farhan Khan',
    category: 'Artificial Intelligence Icon',
    company: 'Allied Blenders & Distillers',
  },
  { name: 'Naveen Gulati', category: 'Artificial Intelligence Icon', company: 'Nykaa' },
  { name: 'Sanjay Kukreja', category: 'Artificial Intelligence Icon', company: 'Eclerx' },
  {
    name: 'Sunil Batra',
    category: 'Blockchain Icon',
    company: 'National Securities Depository (NSDL)',
  },
  { name: 'Abhishek Gupta', category: 'Cloud Icon', company: 'Dish TV' },
  { name: 'Karthick Raja S', category: 'Cloud Icon', company: 'Orient Cement' },
  { name: 'Pankaj Khare', category: 'Cloud Icon', company: 'Indiabulls Housing Finance' },
  { name: 'Satish Panchapakesan', category: 'Cloud Icon', company: 'Arvind Fashions' },
  { name: 'Satish Kumar Dwibhashi', category: 'Cloud Icon', company: 'Inmobi Group' },
  { name: 'Smitesh Shah', category: 'Cloud Icon', company: 'Ambit Finvest' },
  { name: 'Anand Tomar', category: 'CRM Icon', company: "McDonald's India" },
  { name: 'Binita Prasad', category: 'CRM Icon', company: 'Saint-Gobain Grindwell Norton' },
  {
    name: 'Joji Joseph',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'Reliance Power',
  },
  {
    name: 'Srinivas R',
    category: 'Datacenter & IT Infrastructure Icon',
    company: 'The Himalaya Drug Company',
  },
  { name: 'Yogesh Dadke', category: 'Datacenter & IT Infrastructure Icon', company: 'Adient' },
  { name: 'Deena Dayalan K', category: 'DevOps Icon', company: 'Kimberly-Clark Corporation' },
  { name: 'Sanjay Nagpal', category: 'Devops Icon', company: 'TV Today Network' },
  { name: 'Chetan Trivedi', category: 'Digital Icon', company: 'Vedanta' },
  { name: 'Deepak Sharma', category: 'Digital Icon', company: 'Kotak Mahindra Bank' },
  { name: 'Rajesh Kathuria', category: 'Digital Icon', company: 'Entertainment Network India' },
  { name: 'Sonia Swami', category: 'Digital Icon', company: 'O2 Power' },
  { name: 'Swapnil Wadhwa', category: 'Digital Icon', company: 'Aragen Life Sciences' },
  { name: 'Pulak Das', category: 'Edge Computing Icon', company: 'Divgi Torq Transfer Systems' },
  { name: 'Suresh Vijayaraghavan', category: 'Edge Computing Icon', company: 'THG Publishing' },
  { name: 'Abhijit Bhalerao', category: 'ERP Icon', company: 'Lifestyle Business, Raymond' },
  { name: 'Anand Sinha', category: 'ERP Icon', company: 'BirlaSoft' },
  { name: 'Keyur Desai', category: 'ERP Icon', company: 'Essar Ports & Shipping' },
  { name: 'Krishnan Kutty', category: 'ERP Icon', company: 'Gammon Engineers And Contractors' },
  { name: 'Rajeev Mittal', category: 'ERP Icon', company: 'Endurance Technologies' },
  { name: 'Rajesh Panchal', category: 'ERP Icon', company: 'Inox AP' },
  { name: 'Vinod Deshmukh', category: 'ERP Icon', company: 'Haldiram Foods International' },
  { name: 'Shobhana Lele', category: 'ESG Icon', company: 'The Bombay Dyeing and Mfg.' },
  { name: 'Rohit Kilam', category: 'IoT Icon', company: 'CMS Info Systems' },
  { name: 'Satej Revankar', category: 'IoT Icon', company: 'Fiat India Automobiles' },
  { name: 'Venkatesh Babu', category: 'IoT Icon', company: 'COFFEE DAY GLOBAL (CAFE COFFEE DAY)' },
  { name: 'Ajay Bharwani', category: 'IT Modernization Icon', company: 'Writer Corporation' },
  { name: 'Hemang Mehta', category: 'IT Modernization Icon', company: "L'Oréal India" },
  { name: 'Mehjabeen Aalam', category: 'IT Modernization Icon', company: 'Raychem RPG' },
  { name: 'Partha Mondal', category: 'IT Modernization Icon', company: 'Berger Paints India' },
  { name: 'Abhishek Arora', category: 'IT Resilience Icon', company: 'K Raheja Corp' },
  { name: 'Dr. Makarand Sawant', category: 'IT Resilience Icon', company: 'Sahyadri Hospitals' },
  { name: 'Kumaresan M', category: 'IT Resilience Icon', company: 'Unichem Laboratories' },
  { name: 'Balaji Aravamuthan', category: 'IT Services Icon', company: 'Emcure Pharmaceuticals' },
  { name: 'Linson Paul', category: 'IT Services Icon', company: 'Muthoot Microfinanc' },
  { name: 'G.S. Ravi Kumar', category: 'Mobility Icon', company: 'Gati-Kintetsu Express' },
  { name: 'Jitendra Mishra', category: 'Mobility Icon', company: 'Akums Drug & Pharmaceuticals' },
  { name: 'Rajendra Bisht', category: 'Mobility Icon', company: 'Bajaj Finance' },
  { name: 'Sudhir Kanvinde', category: 'Mobility Icon', company: 'The Supreme Industries' },
  { name: 'Amit Phadke', category: 'Productivity Icon', company: 'Toll Group' },
  { name: 'Jai Prakash Sharma', category: 'Productivity Icon', company: 'Info Edge India' },
  { name: 'Kishore Hirani', category: 'Productivity Icon', company: 'Amara Raja Group' },
  { name: 'Nidhi Garg', category: 'Productivity Icon', company: 'Aristocrat Technologies' },
  { name: 'Sarbani Bhatia', category: 'Productivity Icon', company: 'Jagran Prakashan' },
  { name: 'Shankar Venkatesan', category: 'Productivity Icon', company: 'Avalon Technologies' },
  { name: 'Viral Davda', category: 'Productivity Icon', company: 'NCDEX' },
  { name: 'Baskar Raj', category: 'RPA Icon', company: 'Euronet Services India' },
  { name: 'Dhaval Pandya', category: 'RPA Icon', company: 'Piramal Enterprises' },
  { name: 'Satyanarayana Kasturi', category: 'RPA Icon', company: 'Ashok Piramal Group' },
  { name: 'Sekar S', category: 'RPA Icon', company: 'Karur Vysya Bank' },
  { name: 'Manjunath Prasad', category: 'SaaS Icon', company: 'TVS Mobility' },
  { name: 'Mukund K S', category: 'SaaS Icon', company: 'Eris Lifesciences' },
  { name: 'Rajesh Kulkarni', category: 'SaaS Icon', company: 'Piaggio Vehicles' },
  { name: 'Deepak Kolekar', category: 'Secure Digital Workspace Icon', company: 'Godrej Agrovet' },
  {
    name: 'Krishnamurthy Rajesh',
    category: 'Secure Digital Workspace Icon',
    company: 'Grey Orange',
  },
  { name: 'Narendra Sonawane', category: 'Secure Digital Workspace Icon', company: 'Infosys' },
  { name: 'Archie Jackson', category: 'Security Icon', company: 'Incedo Inc.' },
  { name: 'Bhavesh Lakhani', category: 'Security Icon', company: 'Firstsource Solutions' },
  { name: 'Kiran Belsekar', category: 'Security Icon', company: 'Aegon Life Insurance Company' },
  { name: 'Manu Sharma', category: 'Security Icon', company: 'OnMobile Global' },
  { name: 'Purshottam Solanki', category: 'Security Icon', company: 'Dr L H Hiranandani Hospital' },
  { name: 'Pushkar Rege', category: 'Security Icon', company: 'UPL' },
  {
    name: 'Madhusudan Warrier',
    category: 'Software Icon',
    company: 'Mirae Asset Capital Markets India',
  },
  { name: 'Ravi Razdan', category: 'Software Icon', company: 'Jyothy Labs' },
  { name: 'Rishi Sareen', category: 'Transformation Icon', company: 'DTDC Express' },
  { name: 'Subramanya Chandrashekar', category: 'Transformation Icon', company: 'Sagility India' },
];

const businessIconEntries: Winner2023Entry[] = [
  { name: 'A Shiju Rawther', category: 'Asset Management (AMC) Icon', company: 'SBI Mutual Fund' },
  { name: 'Umacharan Singh', category: 'Automobiles & Auto Ancillaries Icon', company: 'CEAT' },
  {
    name: 'Sharad Agarwal',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'JK Tyre & Industries',
  },
  {
    name: 'Rajesh Uppal',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Maruti Suzuki',
  },
  { name: 'Rajiv Arora', category: 'Automobiles & Auto Ancillaries Icon', company: 'Siemens AG' },
  {
    name: 'Rucha Nanavati',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Mahindra Group',
  },
  {
    name: 'Srinivas Rao Kollipara',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Brakes India',
  },
  {
    name: 'Suresh Komrishetty',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Mercedes Benz India',
  },
  {
    name: 'Vinod Gopinathan',
    category: 'Automobiles & Auto Ancillaries Icon',
    company: 'Ashok Leyland',
  },
  { name: 'Amit Jaokar', category: 'Banking Icon', company: 'NKGSB Bank' },
  { name: 'Nilesh Sangoi', category: 'Banking Icon', company: 'Fincare Small Finance Bank' },
  { name: 'Sanjay Gupta', category: 'Banking Icon', company: 'Kotak Mahindra Bank' },
  {
    name: 'Subhash Singh Punjabi',
    category: 'Chemicals Icon',
    company: 'Deepak Fertilisers & Petrochemicals',
  },
  { name: 'Harnath Babu', category: 'Consulting Icon', company: 'KPMG India' },
  { name: 'Mani Mulki', category: 'Diversified Group Icon', company: 'Kedaara Capital' },
  {
    name: 'Rajkumar Ayyella',
    category: 'Engineering Icon',
    company: 'KEC International (RPG Group)',
  },
  { name: 'Abhijit Singh', category: 'Financial Services Icon', company: 'HDFC LTD' },
  {
    name: 'Amit Mahajan',
    category: 'Financial Services Icon',
    company: 'Central Depository Services (India)',
  },
  {
    name: 'Ananth Subramanian',
    category: 'Financial Services Icon',
    company: 'Kotak Mahindra AMC',
  },
  { name: 'Kersi Tavadia', category: 'Financial Services Icon', company: 'Bombay Stock Exchange' },
  {
    name: 'Harish Sharma C L',
    category: 'Financial Services Icon',
    company: 'Toyota Financial Services',
  },
  { name: 'Riyaz Ladiwala', category: 'Financial Services Icon', company: 'Nuvama Wealth' },
  { name: 'Kamal Karnataka', category: 'FMCG Icon', company: 'RJ Corp' },
  {
    name: 'Chandresh Dedhia',
    category: 'Healthcare & Pharma Icon',
    company: 'API Holdings (Pharmeasy)',
  },
  { name: 'Sreeji Gopinathan', category: 'Healthcare & Pharma Icon', company: 'Lupin' },
  {
    name: 'Girish Koppar',
    category: 'Healthcare & Pharma Icon',
    company: 'Central Wockhardt Hospitals',
  },
  { name: 'Manish Kishore', category: 'Healthcare & Pharma Icon', company: 'Wockhardt' },
  { name: 'Mayank Bhargava', category: 'Healthcare & Pharma Icon', company: 'Fortis Healthcare' },
  {
    name: 'Prashant Singh',
    category: 'Healthcare & Pharma Icon',
    company: 'MaxHealthcare Institute',
  },
  { name: 'Sanjay Moralwar', category: 'Healthcare & Pharma Icon', company: 'Zydus Lifesciences' },
  { name: 'Ayan De', category: 'Insurance Icon', company: 'HDFC Life' },
  { name: 'Goutam Datta', category: 'Insurance Icon', company: 'Acko General Insurance' },
  { name: 'Kirti Patil', category: 'Insurance Icon', company: 'Kotak Life Insurance' },
  { name: 'Naseem Halder', category: 'Insurance Icon', company: 'Acko General Insurance' },
  { name: 'Rupesh Mehta', category: 'Insurance Icon', company: 'TATA AIA Life Insurance' },
  { name: 'Anuj Joshi', category: 'IT, BPO & ITES Icon', company: 'Evalueserve' },
  { name: 'Baljinder Singh', category: 'IT, BPO & ITES Icon', company: 'EXL Services' },
  { name: 'Debashis Singh', category: 'IT, BPO & ITES ICON', company: 'Persistent Systems' },
  { name: 'Kuldeep Koul', category: 'IT, BPO & ITES Icon', company: 'Thales India' },
  { name: 'Nayan Desai', category: 'IT, BPO & ITES Icon', company: 'WNS Global Services' },
  { name: 'Gyan Pandey', category: 'Manufacturing Icon', company: 'Voltas' },
  { name: 'Jitendra Singh', category: 'Manufacturing Icon', company: 'JK Cement' },
  { name: 'Nikhil Chaturvedi', category: 'Manufacturing Icon', company: 'JSW' },
  { name: 'Sumi Vivek', category: 'Manufacturing Icon', company: 'Tata Electronics' },
  {
    name: 'Mahendra Upadhyay',
    category: 'Media & Entertainment Icon',
    company: 'Broadcast Audience Research Council (BARC)',
  },
  { name: 'Ayaskant Mohapatra', category: 'NBFC Icon', company: 'BOB Financial Solutions' },
  { name: 'Sendil Kumar Venkatesan', category: 'NBFC Icon', company: 'Shriram Capital' },
  { name: 'Saugata Basu', category: 'Realty Icon', company: 'kalpataru Group' },
  { name: 'Kiran Komatla', category: 'Retail Icon', company: 'Restaurant Brands Asia' },
  {
    name: 'Praveen Shrikiande',
    category: 'Retail Icon',
    company: 'Aditya Birla Fashion and Retail',
  },
  { name: 'Rahul Puri', category: 'Retail Icon', company: 'Devyani International' },
  { name: 'Saugat Dutta', category: 'Retail Icon', company: 'Reliance Retail' },
  { name: 'Vinod Kapote', category: 'Retail Icon', company: 'Trent' },
  { name: 'Apoorv Srivastava', category: 'Telecom Icon', company: 'British Telecom' },
  { name: 'Vinod Krishnan', category: 'Telecom Icon', company: 'Indus Towers' },
  { name: 'Prasad Dhumal', category: 'Transport & Logistics Icon', company: 'DHL Express (India)' },
  {
    name: 'Ashish Mathur',
    category: 'Transport & Logistics Icon',
    company: 'ECU Worldwide (Allcargo Group Company)',
  },
  { name: 'Amit Madhan', category: 'Travel & Hospitality Icon', company: 'Thomas Cook' },
  {
    name: 'Vinod Bhat',
    category: 'Travel & Hospitality Icon',
    company: 'Vistara - Tata SIA Airlines',
  },
];

export const winner2023Sections: Winner2023Section[] = [
  {
    title: 'Technology Icons',
    entries: technologyIconEntries,
  },
  {
    title: 'Business Icons',
    entries: businessIconEntries,
  },
];
